services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build:
      context: ./apps/auth-service
    container_name: auth-service
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./apps/auth-service:/app
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  user-service:
    build:
      context: ./apps/user-service
      dockerfile: Dockerfile
    container_name: user-service
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./apps/user-service:/app
    ports:
      - "8001:8001"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  user-consumer:
    build:
      context: ./apps/user-service
      dockerfile: Dockerfile.consumer
    container_name: user-consumer
    command: python manage.py consume_user_created
    volumes:
      - ./apps/user-service:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - user-service